# Generated by Django 3.0.8 on 2020-08-04 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0002_auto_20200804_1500'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['-population'], 'verbose_name': 'city', 'verbose_name_plural': 'cities'},
        ),
        migrations.AddField(
            model_name='city',
            name='population',
            field=models.IntegerField(default=0, max_length=100, verbose_name='population'),
        ),
    ]
